Changes made and updated the HTTP response as per the TEST cases results
overture-stack/ego pull request #683
Opened 2023-04-05 17:50 UTC by Azher2Ali

Changes made and updated the HTTP response as per the TEST cases results

2023-04-05 18:13 UTC, joneubank requested changes
Thanks for updating the unit tests as well...

For the test cases where the API Key is rejected, its good that we are responding with `OK` but we should also be checking that the response includes `valid: false`

2023-04-12 14:11 UTC, joneubank requested changes
This needs attention. The code does not compile as written and does not test for the case we expect. I left comments with additional details.

2023-04-12 14:11 UTC, joneubank commented on src/test/java/bio/overture/ego/controller/ApiKeyControllerTest.java
> +    assertEquals("false", response.getStatusCode());*/
Please remove unused comments.

2023-04-12 14:11 UTC, joneubank commented on src/test/java/bio/overture/ego/controller/ApiKeyControllerTest.java
> +      assertEquals(HttpStatus.BAD_REQUEST, "false");*/
We should be doing tests on the structure we expect to see:

statusCode = OK
body.valid = false

2023-04-12 14:11 UTC, joneubank commented on src/test/java/bio/overture/ego/controller/TokensOnPermissionsChangeTest.java
> +    assertEquals(checkTokenAfterDeleteResponse.getStatusCode(), HttpStatus.OK);
all the checks for revoked token in this test file are incomplete. a response with status OK can be either valid or invalid. We also need to check if the response has the property `valid: false`

2023-04-12 15:46 UTC, joneubank commented
I've been doing some thinking about these changes... I think we should remove the changes from the other PR instead of pushing through with test case updates. The changes this causes will affect consuming applications.. this is a breaking change that I didn't prepare for thoroughly enough.

If we are going to make these changes, we need to provide a new endpoint (perhaps versioned as v2) and have clearer documentation about the response type. We should also include the same "valid" property with `valid: true` on success.  All in all, this was poorly conceived and prepared for by myself and for now I think we should revert... I'll help prep a PR to pull these changes out.

2023-04-12 16:30 UTC, justincorrigible commented
Closing as result of https://github.com/overture-stack/ego/pull/684

2023-04-12 16:30 UTC, closed without merging